config/routes.rb
Rails.application.routes.draw do

	# root 'pages#index'

	get 'about', to: 'pages#about', as: :about

	get 'privacy', to: 'pages#privacy', as: :privacy

	get 'terms', to: 'pages#terms', as: :terms

	get 'compliance', to: 'pages#compliance', as: :compliance

	get 'random_user', to: 'users#get_random_user', as: :random_user

	get 'check_username', to: 'pages#check_username', as: :check_username

	get 'check_email', to: 'pages#check_email', as: :check_email

	match 'validate_user', to: 'pages#validate_user', via: :post, as: :validate_user

	match 'search', to: 'users#search', via: [:get, :post], as: :user_search
	match 'plans/receive', to: 'plans#receive', via: [:get, :post], defaults: { format: 'json' }, constraints: WhitelistConstraint.new
	get '/photos/:id/images', to: 'users#get_image'
	get '/videos/:id/videos', to: 'users#get_video'

	authenticated :user do
		root to: 'users#user_dashboard', as: :authenticated_root
	end

	unauthenticated do
		root 'pages#index'
	end

	concern :photogenic do
		resources :photos
	end

	resources :users do
		get 'user_dashboard', on: :member
		get 'online_users', on: :collection
		concerns :photogenic
		resources :videos
		resources :profiles
	end

	resources :inboxes
	resources :user_messages do
		get 'sent_messages', on: :collection
	end
	resources :conversations
	resources :subscriptions
	resources :plans, only: [:index]

	devise_for :users, :path => 'accounts', controllers: { confirmations: 'confirmations', sessions: 'sessions', registrations: 'registrations' }

	resources :messages
	resources :friendships

	namespace :admin do
		root 'dashboard#index'
		resources :users, only: [:index, :show]
		resources :user_messages
		resources :plans
	end
end

app/models/video.rb
class Video < ActiveRecord::Base
	belongs_to :user, counter_cache: true

	Paperclip.interpolates :user_id do |attachment, style|
		"user_#{attachment.instance.user_id.to_s}"
	end

	attachment_virtual_path = "/system/attachments/:rails_env/:hashed_path/:user_id/videos/:id/:style/:basename.:extension"
	attachment_real_path = ":rails_root/public" + attachment_virtual_path

	has_attached_file :video,
										:styles => { :thumb => { :geometry => '50x50#', :format => 'jpg'} },
										:processors => [:ffmpeg],
										:path => attachment_real_path,
										:url => attachment_virtual_path

	validates :video, presence: true, on: :create
	validates_attachment_content_type :video, :content_type => /\Avideo\/.*\Z/
end

app/controllers/videos_controller.rb
class VideosController < BaseController
	before_filter :load_user

	def index
		@videos = @user.videos
		authorize @videos
	end

	def show
		@video = @user.videos.find(params[:id])
		authorize @video
		respond_to do |format|
			format.js {}
		end
	end

	def new
		@video = @user.videos.new
		authorize @video
	end

	def create
		@video = @user.videos.new(video_params)
		authorize @video
		respond_to do |format|
			if @video.save
				format.html { redirect_to [@user, @video], notice: 'Video was created successfully'}
			else
				format.html { render action: 'new' }
			end
		end
	end

	def edit
		@video = @user.videos.find(params[:id])
		authorize @video
	end

	def update
		@video = @user.videos.find(params[:id])
		authorize @video
		respond_to do |format|
			if @video.update(video_params)
				format.html { redirect_to @video, notice: t('video_update_success') }
				format.json { head :no_content }
			else
				format.html { render action: 'edit' }
				format.json { render json: @video.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		@video = @user.videos.find(params[:id])
		authorize @video
		@video.destroy
		respond_to do |format|
			format.html { redirect_to user_videos_path }
			format.json { head :no_content }
		end
	end

	private

	def video_params
		params.require(:video).permit(:user_id, :video)
	end

	def load_user
		@user = User.find(params[:user_id])
	end
end

app/views/videos/_form.html.erb
<% provide :title, 'Add Video' %>
<%= form_for [@user, @video], html: { multipart: true} do |f| %>
	<% if @video.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@video.errors.count, 'error') %> prohibited this video from being saved</h2>
			<ul class="no-bullet">
				<% @video.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<div class="row">
		<div class="small-12 columns">
			<%= f.label :video %>
			<%= f.file_field :video %>
		</div>
	</div>
	<div class="row">
		<div class="small-12 columns">
			<%= f.submit 'Add Video', class: 'button tiny radius' %>
		</div>
	</div>
<% end %>

app/views/videos/index.html.erb
<% provide :title, "#{@user.username}'s Videos" %>
<div class="middle-wrapper">
	<section id="videos_index" class="section-padding">
		<div class="row">
			<div class="large-2 columns">
				<article class="panel-default">
					<header class="panel-heading">
						<h4>Options</h4>
					</header>
					<div class="panel-body">
						<ul class="side-nav">
							<% if policy(@user).add_video? %>
								<li><%= link_to 'Add Video', new_user_video_path(@user) %></li>
							<% end %>
							<li><%= link_to 'Photos', user_photos_path(@user) %></li>
							<li><%= link_to 'Profile', user_profile_path(@user, @user.profile) %></li>
						</ul>
					</div>
				</article>
			</div>
			<div class="large-10 columns">
				<article class="panel-default">
					<header class="panel-heading">
						<h4><%= @user.username %>'s videos</h4>
					</header>
					<div class="panel-body">
						<% if @videos.empty? %>
							<div class="row">
								<p class="small-12 columns">This user has no videos uploaded at this time.</p>
							</div>
						<% else %>
							<ul class="small-block-grid-2 large-block-grid-6">
								<% @videos.each do |video| %>
									<%= link_to image_tag(video.video.url(:thumb)), '#', class: 'videobox', data: { href: user_video_path(user_id: @user.id, id: video.id) } %>
								<% end %>
							</ul>
						<% end %>
					</div>
				</article>
			</div>
		</div>
	</section>
</div>

app/views/videos/new.html.erb
<div class="middle-wrapper">
	<section id="new_video" class="section-padding">
		<div class="row">
			<div class="large-2 columns">
				<article class="panel-default">
					<header class="panel-heading">
						<h4>Options</h4>
					</header>
					<div class="panel-body">
						<ul class="side-nav">
							<li><%= link_to 'Videos', user_videos_path(@user) %></li>
							<li><%= link_to 'Photos', user_photos_path(@user) %></li>
							<li><%= link_to 'Profile', user_profile_path(@user, @user.profile) %></li>
						</ul>
					</div>
				</article>
			</div>
			<div class="large-10 columns">
				<article class="panel-default">
					<header class="panel-heading">
						<h4>Add a Video</h4>
					</header>
					<div class="panel-body">
						<%= render 'form' %>
					</div>
				</article>
			</div>
		</div>
	</section>
</div>

app/views/videos/show.html.erb
<video height="400" width="400" class="video_<%= @user.id %>">
	<source type="video/mp4" src="<%= @video.video.url %>">
	<object width="400" height="400" type="application/x-shockwave-flash" data="flashmediaelement.swf">
		<param name="movie" value="flashmediaelement.swf">
		<param name="flashvars" value="controls=true&file=<%= @video.video.url %>">
	</object>
</video>