config/routes.rb
Rails.application.routes.draw do

	# root 'pages#index'

	get 'about', to: 'pages#about', as: :about

	get 'privacy', to: 'pages#privacy', as: :privacy

	get 'terms', to: 'pages#terms', as: :terms

	get 'compliance', to: 'pages#compliance', as: :compliance

	get 'random_user', to: 'users#get_random_user', as: :random_user

	get 'check_username', to: 'pages#check_username', as: :check_username

	get 'check_email', to: 'pages#check_email', as: :check_email

	match 'validate_user', to: 'pages#validate_user', via: :post, as: :validate_user

	match 'search', to: 'users#search', via: [:get, :post], as: :user_search
	match 'plans/receive', to: 'plans#receive', via: [:get, :post], defaults: { format: 'json' }, constraints: WhitelistConstraint.new
	get '/photos/:id/images', to: 'users#get_image'
	get '/videos/:id/videos', to: 'users#get_video'

	authenticated :user do
		root to: 'users#user_dashboard', as: :authenticated_root
	end

	unauthenticated do
		root 'pages#index'
	end

	concern :photogenic do
		resources :photos
	end

	resources :users do
		get 'user_dashboard', on: :member
		get 'online_users', on: :collection
		concerns :photogenic
		resources :videos
		resources :profiles
	end

	resources :inboxes
	resources :user_messages do
		get 'sent_messages', on: :collection
	end
	resources :conversations
	resources :subscriptions
	resources :plans, only: [:index]

	devise_for :users, :path => 'accounts', controllers: { confirmations: 'confirmations', sessions: 'sessions', registrations: 'registrations' }

	resources :messages
	resources :friendships

	namespace :admin do
		root 'dashboard#index'
		resources :users, only: [:index, :show]
		resources :user_messages
		resources :plans
	end
end

app/views/shared/_errors.html.erb
<% if model.errors.any? %>
	<div id="error_explanation">
		<%= pluralize(model.errors.count, 'error') %> prohibited this from being saved:
		<ul>
			<% model.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_flash.html.erb
<div id="flash">
	<% flash.each do |name, msg| %>
		<% if msg.is_a?(String) %>
			<div data-alert class="alert-box <%= flash_class(name) %>">
				<%= msg %>
				<a href="#" class="close">&times;</a>
			</div>
		<% end %>
	<% end %>
</div>

app/views/shared/_landing_img.html.erb
<section id="landing-top" class="clearfix">
	<% unless user_signed_in? %>
		<div class="row">
			<section class="large-7 columns">
				<%= render 'shared/flash' %>
			</section>
			<section class="large-5 columns registration-form">
				<header>
					<h2>Sign Up <span class="theme-prim-color">Now</span></h2>
					<h3>Start Hooking Up Tonight!</h3>
				</header>
				<%= render 'devise/registrations/form' %>
			</section>
		</div>
	<% end %>
</section>

app/views/shared/_landing_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button class="navbar-toggle" data-toggle="collapse" type="button" data-target="#top_nav_collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
		</div>
		<div id="top_nav_collapse" class="collapse navbar-collapse">
			<% if user_signed_in? %>
				<ul class="nav navbar-nav">
					<%= nav_link('Home', user_dashboard_user_path(current_user), 'home')  %>
				</ul>
				<ul class="nav navbar-nav">
					<li class="dropdown">
						<a class="dropdown-toggle" href="#" data-toggle="dropdown">
							<span class="glyphicon glyphicon-user"></span>
							<%= current_user.email %>
							<b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li>
								<%= link_to 'Logout', destroy_user_session_path, method: :delete %>
							</li>
							<% if current_user.is_admin? %>
								<li>
									<%= link_to 'Administration', admin_root_path %>
								</li>
							<% end %>
						</ul>
					</li>
				</ul>
			<% end %>
		</div>
	</div>
</nav>

app/views/shared/_landing_registration_sent.html.erb
<header>
	<h2>Thank you for registering</h2>
	<h3>Did not recieve confirmation email?</h3>
	<%= render 'devise/confirmations/form' %>
</header>

app/views/shared/_login_links.html.erb
<% if user_signed_in? %>
	<ul class="left">
		<%= nav_link('Home', user_dashboard_user_path(current_user), 'home') %>
		<li class="divider"></li>
		<%= nav_link('Search', user_search_path, 'search') %>
		<li class="divider"></li>
		<%= nav_link('Online', online_users_users_path, 'link') %>
		<li class="divider"></li>
		<li class=<% (current_page?(user_messages_path) ? 'active' : '') %>>
			<%= link_to user_messages_path do %>
				<span class="fa fa-envelope"></span>
				Inbox
				<span class="label radius">
					<%= current_user.user_messages.unread.count %>
				</span>
			<% end %>
		</li>
	</ul>
	<ul class="right">
		<% unless current_user.is_vip? || current_user.is_admin? %>
			<li class="has-form">
				<%= link_to 'Upgrade Now', plans_path, class: 'small button radius' %>
			</li>
		<% end %>
		<li class="has-dropdown">
			<a href="#">
				<%= image_tag(current_user.avatar_photo_url(:tiny), class: 'nav-user-photo') %>
				<div class="user-info">
					<small>
						<%= current_user.role %>
					</small>
					<%= current_user.email %>
				</div>
			</a>
			<ul class="dropdown">
				<li><%= link_to 'Add Photos', user_photos_path(current_user) %></li>
				<li><%= link_to 'Add Videos', user_videos_path(current_user) %></li>
				<li><%= link_to 'Edit Profile', edit_user_profile_path(current_user, current_user.profile.id) %></li>
				<li><%= link_to 'My Profile', user_profile_path(current_user, current_user.profile) %></li>
				<% if current_user.is_admin? %>
					<li><%= link_to 'Administration', admin_root_path%></li>
				<% end %>
				<li><%= link_to('Logout', destroy_user_session_path, method: :delete)%></li>
			</ul>
		</li>
	</ul>
<% else %>
	<ul class="right">
		<li><%= link_to('Login', new_user_session_path) %></li>
		<li><%= link_to 'Sign up', new_user_registration_path %></li>
	</ul>
<% end %>

app/views/shared/_login_modal.html.erb
<div class="reveal-modal tiny" data-reveal id="login-modal">
	<a class="close-reveal-modal">&#215;</a>
	<div class="row">
		<div class="small-12 columns">
			<h2 class="without-margins text-center">
				Log In
			</h2>
			<p class="text-center">
				To access your account
			</p>
			<%= render 'devise/sessions/form' %>
		</div>
	</div>
	<div class="row">
		<div class="small-12 columns">
			<%= render "devise/shared/links" %>
		</div>
	</div>
</div>

app/views/shared/_messages.html.erb
<div class="row">
	<div class="notify_bar">
		<div class="col-md-2 col-md-offset-10 chat_notify">
			<%= image_tag(profile.avatar_photo_url(:tiny), size: '15') %>
			<span class="notify_username">
				<%= profile.username %>
			</span>
		</div>
		<div class="col-md-3 col-md-offset-9 chat_window hidden">
			<article class="panel panel-default">
				<header class="panel-heading">
					<span class="glyphicon glyphicon-comment"></span>
					<%= profile.username %>
					<span class="glyphicon glyphicon-remove pull-right"></span>
					<span class="glyphicon glyphicon-minus pull-right"></span>
				</header>
				<div class="panel-body">
					<ul class="chat_body">
						<% unless current_user.vip? %>
							<li>
								<%= image_tag(profile.avatar_photo_url(:tiny)) %>
								<span>Would like to see your photos</span>
							</li>
							<li><%= link_to 'Chat with her', plans_path, class: 'btn chat_promo_btn promo_btn_1' %></li>
							<li><%= link_to 'Not now', '#', class: 'btn chat_promo_btn promo_btn_2' %></li>
						<% end %>
					</ul>
				</div>
				<footer class="panel-footer">
					<div class="input-group">
						<% if current_user.vip? %>
							<input id="btn-input" class="form-control input-sm" type="text" placeholder="Type your message here...">
						<% else %>
							<input id="btn-input" class="form-control input-sm" type="text" placeholder="Upgrade to chat..." disabled>
						<span class="input-group-btn">
							<button class="btn btn-primary btn-sm <% current_user.vip? ? '' : 'disabled' %>" id="btn-chat">Send</button>
						</span>
						<% end %>
					</div>
				</footer>
			</article>
		</div>
	</div>
</div>

app/views/shared/_modal.html.erb
<div id="main-modal" class="reveal-modal" data-reveal>
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<a href="#" class="close-reveal-modal">&#215;</a>
				<h4 class="modal-title"></h4>
			</div>
			<div class="modal-body">
				<div class="modal-body-content"></div>
			</div>
		</div>
	</div>
</div>

app/views/shared/_navigation.html.erb
<nav class="top-bar" data-topbar>
	<ul class="title-area">
		<li class="name">
			<h1>
				<%= link_to image_tag('RA_logo.png'), (user_signed_in? ? user_dashboard_user_path(current_user) : root_path)  %>
			</h1>
		</li>
		<li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
	</ul>
	<section class="top-bar-section">
		<%= render 'shared/login_links' %>
	</section>
</nav>

app/views/shared/_top_bar.html.erb
<div class="hide-for-large-up">
	<div class="row masthead">
		<%= link_to image_tag('RA_logo.png'), root_url, class: 'small-6 columns'  %>
		<div class="small-6 columns text-right">
			<% unless user_signed_in? %>
				<a href="#" data-reveal-id="login-modal" class="button tiny radius">Login</a>
			<% end %>
		</div>
	</div>
	<div class="row">
		<h4 class="tagline text-center">Find horny singles online now in <%= session[:user_info].city_name %></h4>
	</div>
</div>

<div class="row masthead show-for-large-up">
	<%= link_to image_tag('RA_logo.png'), root_url, class: 'small-4 columns' %>
	<div class="small-7 columns text-center">
		<h4 class="tagline without-margins">
			Find horny singles online now in
			<%= session[:user_info].city_name %>
		</h4>
	</div>
	<div class="small-1 columns text-right">
		<% unless user_signed_in? %>
			<a href="#" data-reveal-id="login-modal">Log In</a>
		<% end %>
	</div>
</div>

app/views/shared/_tracking_code.html.erb
<% if Rails.env.production? %>
	<script>
		(function (i, s, o, g, r, a, m)
		{
			i['GoogleAnalyticsObject'] = r;
			i[r] = i[r] || function ()
			{
				(i[r].q = i[r].q || []).push(arguments)
			}, i[r].l = 1 * new Date();
			a = s.createElement(o),
				m = s.getElementsByTagName(o)[0];
			a.async = 1;
			a.src = g;
			m.parentNode.insertBefore(a, m)
		})(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

		ga('create', 'UA-54647014-1', 'auto');
		//ga('send', 'pageview');

	</script>
<% else %>
	<script>
		function ga () {
			var params = Array.prototype.slice.call(arguments, ga.length);
			console.log('GoogleAnalytics: ' + params);
		};
	</script>
<% end %>

app/views/shared/devise_errors.js.erb
if($('#flash').length > 0) {
	$('#flash').remove();
	$('.registration-form').prepend("<%= escape_javascript raw(flash_normal) %>");
}
else {
	$('.registration-form').prepend("<%= escape_javascript raw(flash_normal )%>");
}

app/views/shared/devise_success_sign_up.js.erb
if($('#flash').length > 0) {
	$('#flash').remove();
}
$('.registration-form').html("<%= escape_javascript( render partial: 'shared/landing_registration_sent') %>");