config/routes.rb
Rails.application.routes.draw do

	# root 'pages#index'

	get 'about', to: 'pages#about', as: :about

	get 'privacy', to: 'pages#privacy', as: :privacy

	get 'terms', to: 'pages#terms', as: :terms

	get 'compliance', to: 'pages#compliance', as: :compliance

	get 'random_user', to: 'users#get_random_user', as: :random_user

	get 'check_username', to: 'pages#check_username', as: :check_username

	get 'check_email', to: 'pages#check_email', as: :check_email

	match 'validate_user', to: 'pages#validate_user', via: :post, as: :validate_user

	match 'search', to: 'users#search', via: [:get, :post], as: :user_search
	match 'plans/receive', to: 'plans#receive', via: [:get, :post], defaults: { format: 'json' }, constraints: WhitelistConstraint.new
	get '/photos/:id/images', to: 'users#get_image'
	get '/videos/:id/videos', to: 'users#get_video'

	authenticated :user do
		root to: 'users#user_dashboard', as: :authenticated_root
	end

	unauthenticated do
		root 'pages#index'
	end

	concern :photogenic do
		resources :photos
	end

	resources :users do
		get 'user_dashboard', on: :member
		get 'online_users', on: :collection
		concerns :photogenic
		resources :videos
		resources :profiles
	end

	resources :inboxes
	resources :user_messages do
		get 'sent_messages', on: :collection
	end
	resources :conversations
	resources :subscriptions
	resources :plans, only: [:index]

	devise_for :users, :path => 'accounts', controllers: { confirmations: 'confirmations', sessions: 'sessions', registrations: 'registrations' }

	resources :messages
	resources :friendships

	namespace :admin do
		root 'dashboard#index'
		resources :users, only: [:index, :show]
		resources :user_messages
		resources :plans
	end
end

app/models/friendship.rb
# == Schema Information
#
# Table name: friendships
#
#  id          :integer          not null, primary key
#  user_id     :integer
#  friend_id   :integer
#  status      :string(255)
#  accepted_at :datetime
#  created_at  :datetime
#  updated_at  :datetime
#

class Friendship < ActiveRecord::Base

	belongs_to :user
	belongs_to :friend, class_name: 'User', foreign_key: 'friend_id'

	validates :user_id, :friend_id, presence: true


	after_create do |p|
		Friendship.create!(user_id: p.friend_id, friend_id: p.user_id, status: 'pending') if !Friendship.where(friend_id: p.user_id, user_id: p.friend_id).first
	end

	after_destroy do |p|
		remove_other_side(p.user_id, p.friend_id)
	end

	after_update do |p|
		reciprocal = Friendship.where(friend_id: p.user_id, user_id: p.friend_id).first
		update_other_side_of_friendship(reciprocal, p.friend_id, p.user_id)
	end

	def self.accepted
		where(status: 'accepted')
	end

	def self.pending
		where(status: 'pending')
	end

	def self.requested
		where(status: 'requested')
	end

	private

	def remove_other_side(user_id, friend_id)
		reciprocal = Friendship.where(friend_id: user_id).first
		unless reciprocal.nil?
			reciprocal.destroy
			User.decrement_counter(:friends_count, user_id)
			User.decrement_counter(:friends_count, friend_id)
		end
	end

	def update_other_side_of_friendship(friendship, friend_id, user_id)
		unless friendship.status == 'accepted'
			friendship.update_attribute(:status, 'accepted')
			User.increment_counter(:friends_count, user_id)
			User.increment_counter(:friends_count, friend_id)
		end
	end
end

app/controllers/friendships_controller.rb
class FriendshipsController < BaseController
	#before_filter :setup_friends, except: :index

	def index
		@friendships = current_user.friendships.accepted.includes(:friend => { :profile => :avatar })
		@pending_friendships = current_user.friendships.pending.includes(:friend => { :profile => :avatar })
		@requested_friendships = current_user.friendships.requested.includes(:friend => { :profile => :avatar })
	end

	def create
		@friendship = current_user.friendships.build(friendship_params)
		respond_to do |format|
			if @friendship.save
				format.html { redirect_to root_url, notice: 'Friend request sent.' }
			else
				format.html { redirect_to root_url, notice: 'Unable to add friend.'}
			end
		end
	end

	def update
		@friendship = current_user.friendships.where(friend_id: params[:id]).first
		respond_to do |format|
			if @friendship.update_attribute(:status, 'accepted')
				format.html { redirect_to root_url, notice: 'Accepted friend request' }
			else
				format.html { redirect_to root_url, notice: 'Unable to accept friend request' }
			end
		end
	end

	def destroy
		@friendship = current_user.friendships.find(params[:id])
		@friendship.destroy
		respond_to do |format|
			format.html { redirect_to root_url, notice: 'Removed friendship' }
		end
		authorize! :destroy, @friendship
	end

	private

	def friendship_params
		params.require(:friendship).permit(:friend_id, :user_id, :status)
	end
end

app/helpers/friendship_helper.rb
module FriendshipHelper

	# Example <%= image_link_to "image_path", url_helper, 'you really need to see this' { size: '210x60', alt: 'Somecool Alt'}, { title: 'Something cool', rel: 'tooltip', relative: true } %>  - You get the point
	def image_link_to(image_path, url, image_tag_options = {}, link_to_options = {}, &block)
		link_to url, link_to_options do
			content_tag(:figure) do
				concat image_tag image_path, image_tag_options
				concat content_tag(:figcaption, &block)
			end
		end
	end

	def friendship_status(user, friend)
		friendship = user.check_friendships(friend)
		if friendship.nil?
			return content_tag(:div, class: 'row') do
				concat content_tag(:span, link_to('Add Friend', friendships_path(friendship: {friend_id: friend, status: 'requested'}), method: :post, class: 'btn btn-primary'), class: 'col-md-2')
				#concat content_tag(:span, class: 'col-md-2') do
				#	link_to 'Add Friend', friendships_path(friendship: {friend_id: friend, status: 'requested'}), method: :post, class: 'btn btn-primary'
				#end
				concat content_tag(:span, ' You are not friends (yet)', class: 'col-md-2')
			end
		end

		case friendship.status
			when 'requested'
				content_tag(:span, 'You have already requested friendship')
			when 'pending'
				content_tag(:span, 'This user has already requested you as a friend')
			when 'accepted'
				content_tag(:span, 'You are friends')
			else
				# type code here
		end
	end
end

app/views/friendships/_friends.html.slim
li
  = image_link_to(friendship.friend.profile.avatar_photo_url(:tiny), profile_path(friendship.friend.profile)) do
    p
      = friendship.friend.profile.username
  - if can? :destroy, friendship
    = link_to 'Remove Friend', friendship_path(friendship), method: :delete, data: { confirm: 'Are you sure you want to remove this friendship?' }

app/views/friendships/_pending.html.slim
li
  = image_tag pending_friendship.friend.profile.avatar_photo_url(:thumb)
  p
    = pending_friendship.friend.profile.username
  - if can? :update, pending_friendship
    = link_to 'Accept', friendship_path(pending_friendship.friend), method: 'patch'

app/views/friendships/_requested.html.slim
li
  = image_tag requested_friendship.friend.profile.avatar_photo_url(:tiny)
  p
    = requested_friendship.friend.profile.username

app/views/friendships/index.html.slim
.middle-wrapper
  section#friendship.container.section-padding
    .row
      header
        h2
          | My Friends
      .col-md-2
        ul.nav.nav-pills.nav-stacked
          li.active
            a[href="#friends" data-toggle="tab"]
              | Friends
          li
            a[href="#pending" data-toggle="tab"]
              | Awaiting Action
          li
            a[href="#requested" data-toggle="tab"]
              | Pending Requested
      .tab-content.col-md-9.col-md-offset-1
        #friends.tab-pane.active
          - if @friendships.empty?
            p
              | You are a sad and lonely person and really need to get out more cause you have no damn friends
          - else
            ul.list-inline
              - @friendships.each do |friendship|
                = render 'friendships/friends', friendship: friendship
        #pending.tab-pane
          - if @pending_friendships.empty?
            p
              | No pending
          - else
            ul.list-inline
              - @pending_friendships.each do |pending_friendship|
                = render 'friendships/pending', pending_friendship: pending_friendship
        #requested.tab-pane
          - if @requested_friendships.empty?
            p
              | You have not requested any friends
          - else
            ul.list-inline
              - @requested_friendships.each do |requested_friendship|
                = render 'friendships/requested', requested_friendship: requested_friendship