config/routes.rb
Rails.application.routes.draw do

	# root 'pages#index'

	get 'about', to: 'pages#about', as: :about

	get 'privacy', to: 'pages#privacy', as: :privacy

	get 'terms', to: 'pages#terms', as: :terms

	get 'compliance', to: 'pages#compliance', as: :compliance

	get 'random_user', to: 'users#get_random_user', as: :random_user

	get 'check_username', to: 'pages#check_username', as: :check_username

	get 'check_email', to: 'pages#check_email', as: :check_email

	match 'validate_user', to: 'pages#validate_user', via: :post, as: :validate_user

	match 'search', to: 'users#search', via: [:get, :post], as: :user_search
	match 'plans/receive', to: 'plans#receive', via: [:get, :post], defaults: { format: 'json' }, constraints: WhitelistConstraint.new
	get '/photos/:id/images', to: 'users#get_image'
	get '/videos/:id/videos', to: 'users#get_video'

	authenticated :user do
		root to: 'users#user_dashboard', as: :authenticated_root
	end

	unauthenticated do
		root 'pages#index'
	end

	concern :photogenic do
		resources :photos
	end

	resources :users do
		get 'user_dashboard', on: :member
		get 'online_users', on: :collection
		concerns :photogenic
		resources :videos
		resources :profiles
	end

	resources :inboxes
	resources :user_messages do
		get 'sent_messages', on: :collection
	end
	resources :conversations
	resources :subscriptions
	resources :plans, only: [:index]

	devise_for :users, :path => 'accounts', controllers: { confirmations: 'confirmations', sessions: 'sessions', registrations: 'registrations' }

	resources :messages
	resources :friendships

	namespace :admin do
		root 'dashboard#index'
		resources :users, only: [:index, :show]
		resources :user_messages
		resources :plans
	end
end

app/models/user_message.rb
# TODO need to add a messages_count to users model and add logic so no need to use sql count

class UserMessage < ActiveRecord::Base
	belongs_to :user
	belongs_to :sender, :class_name => "User", :foreign_key => "sender_id"
	belongs_to :inbox, inverse_of: :user_messages

	has_many :children, class_name: 'UserMessage', foreign_key: 'parent_id'
	belongs_to :parent, class_name: 'UserMessage', foreign_key: 'parent_id'

	validates :body, :user, presence: true

	scope :sent, -> { where sent: true }
	scope :received, -> { where sent: false }
	scope :unread, -> { where read: false }
	scope :fake_user_messages, -> { includes(:user, {:sender => :inbox}).where(read: false).where('users.role = ?', 3).references(:user) }

	#def add_user_message(from, recipient, admin=false)
	def add_user_message(sent=true, admin=false)
		# TODO perhaps later we will need a sent
		#msg = self.dup
		#msg.sent = false
		#msg.user_id = recipient.id
		#msg.save
		#self.update_attributes(user_id: from.id, sent: true, read: false)
		#self.update_attributes!(user_id: recipient.id, sender_id: from.id, sent: false, read: false, admin_message: admin)
		self.update_attributes!(sent: sent, read: false, admin_message: admin)
	end

	def is_admin_message?
		self.admin_message?
	end

	def mark_as_read
		self.update_attributes!(read: true)
		if self.children.count > 0
			self.children.includes(:user).each do |child|
				child.update_attributes!(read: true)
			end
		end
	end

	def mark_as_unread
		self.update_attributes!(read: false)
	end

	def from
		User.find(self.sender_id)
	end

end

app/controllers/admin/user_messages_controller.rb
class Admin::UserMessagesController < Admin::BaseController
	before_filter :load_inbox, only: [:show, :create]
	def index
		@user_messages = UserMessage.fake_user_messages.order(created_at: :desc)
	end

	def show
		@user_message = UserMessage.find(params[:id])
		@user_message.mark_as_read
	end

	def new
		def new
			@user_message = UserMessage.new
			@recipient = User.find(params[:recipient_id])
		end
	end

	def create
		@user_message = @inbox.user_messages.new(user_message_params)
		respond_to do |format|
			if @user_message.add_user_message(false)
				format.html { redirect_to admin_user_messages_path, notice: 'Message was successfully created.' }
				format.json { render action: 'show', status: :created, location: @user_message }
			else
				format.html { render action: 'new' }
				format.json { render json: @user_message.errors, status: :unprocessable_entity }
			end
		end
	end

	private

	def load_inbox
		@inbox = Inbox.find(params[:inbox_id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def user_message_params
		#params[:user_message]
		params.require(:user_message).permit(:sender_id, :body, :subject, :user_id, :parent_id)
	end
end

app/controllers/user_messages_controller.rb
class UserMessagesController < BaseController
	before_filter :load_recipient_and_inbox, only: [:new, :create, :show]

  def index
		@inbox = current_user.inbox
		authorize @inbox
		@user_messages = @inbox.user_messages.where(parent_id: nil).includes(:user, {:sender => [:avatar]}).received.order(created_at: :desc)
  end

  # GET /user_messages/1
  # GET /user_messages/1.json
  def show
		# @user_message.mark_as_read
		@inbox = current_user.inbox
		@user_message = @inbox.user_messages.includes(:user).find(params[:id])
		authorize @user_message
		@children = @user_message.children.includes(:user, :sender).order(created_at: :asc)
		@user_message.mark_as_read
  end

  # GET /user_messages/new
  def new
		@user_message = @inbox.user_messages.new
		authorize @user_message
  end

  # GET /user_messages/1/edit
  def edit
  end

  # POST /user_messages
  # POST /user_messages.json
  def create
		@user_message = @inbox.user_messages.new(user_message_params)
    respond_to do |format|
			if @user_message.add_user_message
				unless @recipient.fake?
					MainMailer.user_sent_inbox_message(@recipient, @user_message.sender).deliver
				else
					MainMailer.send_message_to_fake_user_to_admin(@user_message, @user_message.sender).deliver
				end
        format.html { redirect_to user_messages_path, notice: 'User message was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user_message }
      else
        format.html { render action: 'new' }
        format.json { render json: @user_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_messages/1
  # PATCH/PUT /user_messages/1.json
  def update
		@inbox = current_user.inbox
		@user_message = @inbox.user_messages.find(params[:id])
    respond_to do |format|
      if @user_message.update(user_message_params)
        format.html { redirect_to @user_message, notice: 'User message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user_message.errors, status: :unprocessable_entity }
      end
    end
	end

	def sent_messages
		@user_messages = current_user.sent_user_messages.includes(:user => :avatar)
	end

  # DELETE /user_messages/1
  # DELETE /user_messages/1.json
  def destroy
		@user_message.find(params[:id])
    @user_message.destroy
    respond_to do |format|
      format.html { redirect_to user_messages_url }
      format.json { head :no_content }
    end
  end

  private

	def load_recipient_and_inbox
		@recipient = User.find(params[:user])
		@inbox = @recipient.inbox
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def user_message_params
		params.require(:user_message).permit(:sender_id, :body, :subject, :user_id, :parent_id)
	end
end

app/helpers/user_messages_helper.rb
module UserMessagesHelper
end

app/views/admin/user_messages/index.html.erb
<% provide :title, 'User Messages' %>
<div class="middle-wrapper">
  <section class="container section-padding">
    <div class="row">
      <div class="col-md-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4>User messages</h4>
					</div>
          <div class="panel-body">
            <table class="table table-bordered">
              <thead>
                <tr>
                  <th>Recipient</th>
                  <th>Sender</th>
                  <th>Received</th>
                  <th>Options</th>
								</tr>
							</thead>
              <tbody>
                <% @user_messages.each do |user_message| %>
                  <tr>
                    <td><%= user_message.user.email %></td>
                    <td><%= user_message.sender.email %>
                    <td><%= time_ago_in_words(user_message.created_at) %> ago</td>
                    <td><%= link_to 'Show', admin_user_message_path(user_message, inbox_id: user_message.sender.inbox.id) %></td>
									</tr>
								<% end %>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</section>
</div>

app/views/admin/user_messages/show.html.erb
<% provide :title, 'Message' %>
<div class="middle-wrapper">
  <section id="message" class="container section-padding">
  	<div class="row">
      <div class="col-md-12">
        <article class="panel panel-default">
          <header class="panel-heading">
            <h4>
            	Message from
              <%= @user_message.sender.username %> to <%= @user_message.user.username %>
            </h4>
					</header>
          <div class="panel-body">
            <%= @user_message.body %>
          </div>
          <footer class="panel-footer">
            <%= form_for [:admin, UserMessage.new], html: {class: 'form-horizontal'} do |f| %>
              <%= hidden_field_tag :inbox_id, @inbox.id %>
              <%= f.hidden_field :sender_id, value: @user_message.user_id %>
              <%= f.hidden_field :user_id, value: @user_message.sender.id %>
              <% if @user_message.parent_id %>
                <%= f.hidden_field :parent_id, value: @user_message.parent_id %>
              <% end %>
              <%= hidden_field_tag :inbox_id, @inbox.id %>
              <div class="form-group no-bottom-margin">
                <div class="col-md-6">
                  <%= f.text_field :body, class: 'form-control' %>
                </div>
                <%= f.submit 'Send Reply', class: 'btn btn-primary col-md-2' %>
							</div>
						<% end %>
					</footer>
				</article>
			</div>
		</div>
	</section>
</div>